settings:
  title: 'Status Page'
  url: 'https://status.chiziingiin.top' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: chiziingiin # unique identifier
    name: www.chiziingiin.top
    description: '记录学习与思考' # default=empty
    url: 'https://www.chiziingiin.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: lingben-chiziingiin
    name: 零本智协
    description: '依托领先的多模型深度思考 AI 技术驱动力量，构建全面创新的市场项目解决方案体系，致力于让「零成本构建创新高效应用程序」成为现实。'
    url: 'https://lingben.chiziingiin.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: lingben-chiziingiin-api
    name: 零本智协API
    url: 'https://lingben.chiziingiin.top/api/test'
    method: GET
    expectStatus: 200
    linkable: false
